module.exports =
    {
        PARENT_NOT_FOUND: "PARENT_NOT_FOUND",
        INVALID_INGREDIENT: "INVALID_INGREDIENT",
        ERROR_TRAINING_NOT_FOUND: "ERROR_TRAINING_NOT_FOUND",
        ERROR_EXERCISE_NOT_FOUND:"ERROR_EXERCISE_NOT_FOUND"
    }